// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: github.com/pomerium/envoy-custom/api/extensions/bootstrap/dynamic_extension_loader/dynamic_extension_loader.proto

package dynamic_extension_loader

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of paths on disk to load extensions.
	Paths []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	// Opaque configuration by extension ID
	ExtensionConfigs map[string]*anypb.Any `protobuf:"bytes,4,rep,name=extension_configs,json=extensionConfigs,proto3" json:"extension_configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *Config) GetExtensionConfigs() map[string]*anypb.Any {
	if x != nil {
		return x.ExtensionConfigs
	}
	return nil
}

var File_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto protoreflect.FileDescriptor

const file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_rawDesc = "" +
	"\n" +
	"qgithub.com/pomerium/envoy-custom/api/extensions/bootstrap/dynamic_extension_loader/dynamic_extension_loader.proto\x12,pomerium.extensions.dynamic_extension_loader\x1a\x19google/protobuf/any.proto\"\xf2\x01\n" +
	"\x06Config\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\x12w\n" +
	"\x11extension_configs\x18\x04 \x03(\v2J.pomerium.extensions.dynamic_extension_loader.Config.ExtensionConfigsEntryR\x10extensionConfigs\x1aY\n" +
	"\x15ExtensionConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01BTZRgithub.com/pomerium/envoy-custom/api/extensions/bootstrap/dynamic_extension_loaderb\x06proto3"

var (
	file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_rawDescOnce sync.Once
	file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_rawDescData []byte
)

func file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_rawDescGZIP() []byte {
	file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_rawDescOnce.Do(func() {
		file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_rawDesc), len(file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_rawDesc)))
	})
	return file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_rawDescData
}

var file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_goTypes = []any{
	(*Config)(nil),    // 0: pomerium.extensions.dynamic_extension_loader.Config
	nil,               // 1: pomerium.extensions.dynamic_extension_loader.Config.ExtensionConfigsEntry
	(*anypb.Any)(nil), // 2: google.protobuf.Any
}
var file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_depIdxs = []int32{
	1, // 0: pomerium.extensions.dynamic_extension_loader.Config.extension_configs:type_name -> pomerium.extensions.dynamic_extension_loader.Config.ExtensionConfigsEntry
	2, // 1: pomerium.extensions.dynamic_extension_loader.Config.ExtensionConfigsEntry.value:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() {
	file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_init()
}
func file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_init() {
	if File_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_rawDesc), len(file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_goTypes,
		DependencyIndexes: file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_depIdxs,
		MessageInfos:      file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_msgTypes,
	}.Build()
	File_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto = out.File
	file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_goTypes = nil
	file_github_com_pomerium_envoy_custom_api_extensions_bootstrap_dynamic_extension_loader_dynamic_extension_loader_proto_depIdxs = nil
}
