// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: github.com/pomerium/envoy-custom/api/x/mirroring/mirroring.proto

package mirroring

import (
	v3 "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	ssh "github.com/pomerium/envoy-custom/api/extensions/filters/network/ssh"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MirrorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*MirrorRequest_Metadata
	//	*MirrorRequest_Data
	//	*MirrorRequest_Event
	Request       isMirrorRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MirrorRequest) Reset() {
	*x = MirrorRequest{}
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MirrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MirrorRequest) ProtoMessage() {}

func (x *MirrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MirrorRequest.ProtoReflect.Descriptor instead.
func (*MirrorRequest) Descriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDescGZIP(), []int{0}
}

func (x *MirrorRequest) GetRequest() isMirrorRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *MirrorRequest) GetMetadata() *StreamMetadata {
	if x != nil {
		if x, ok := x.Request.(*MirrorRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *MirrorRequest) GetData() *StreamData {
	if x != nil {
		if x, ok := x.Request.(*MirrorRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *MirrorRequest) GetEvent() *StreamEvent {
	if x != nil {
		if x, ok := x.Request.(*MirrorRequest_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isMirrorRequest_Request interface {
	isMirrorRequest_Request()
}

type MirrorRequest_Metadata struct {
	Metadata *StreamMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type MirrorRequest_Data struct {
	Data *StreamData `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type MirrorRequest_Event struct {
	Event *StreamEvent `protobuf:"bytes,3,opt,name=event,proto3,oneof"`
}

func (*MirrorRequest_Metadata) isMirrorRequest_Request() {}

func (*MirrorRequest_Data) isMirrorRequest_Request() {}

func (*MirrorRequest_Event) isMirrorRequest_Request() {}

type MirrorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*MirrorResponse_Hello
	//	*MirrorResponse_Pause
	//	*MirrorResponse_Resume
	Response      isMirrorResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MirrorResponse) Reset() {
	*x = MirrorResponse{}
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MirrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MirrorResponse) ProtoMessage() {}

func (x *MirrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MirrorResponse.ProtoReflect.Descriptor instead.
func (*MirrorResponse) Descriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDescGZIP(), []int{1}
}

func (x *MirrorResponse) GetResponse() isMirrorResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *MirrorResponse) GetHello() *ReceiverHello {
	if x != nil {
		if x, ok := x.Response.(*MirrorResponse_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *MirrorResponse) GetPause() *PauseRequest {
	if x != nil {
		if x, ok := x.Response.(*MirrorResponse_Pause); ok {
			return x.Pause
		}
	}
	return nil
}

func (x *MirrorResponse) GetResume() *ResumeRequest {
	if x != nil {
		if x, ok := x.Response.(*MirrorResponse_Resume); ok {
			return x.Resume
		}
	}
	return nil
}

type isMirrorResponse_Response interface {
	isMirrorResponse_Response()
}

type MirrorResponse_Hello struct {
	// ReceiverHello must be the first response received and must be sent by the server immediately
	// on connect. There is a 5 second timeout between the client starting the stream until the
	// ReceiverHello is received, or the session will be terminated.
	Hello *ReceiverHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type MirrorResponse_Pause struct {
	Pause *PauseRequest `protobuf:"bytes,2,opt,name=pause,proto3,oneof"`
}

type MirrorResponse_Resume struct {
	Resume *ResumeRequest `protobuf:"bytes,3,opt,name=resume,proto3,oneof"`
}

func (*MirrorResponse_Hello) isMirrorResponse_Response() {}

func (*MirrorResponse_Pause) isMirrorResponse_Response() {}

func (*MirrorResponse_Resume) isMirrorResponse_Response() {}

type ReceiverHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiverHello) Reset() {
	*x = ReceiverHello{}
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiverHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiverHello) ProtoMessage() {}

func (x *ReceiverHello) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiverHello.ProtoReflect.Descriptor instead.
func (*ReceiverHello) Descriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDescGZIP(), []int{2}
}

type StreamMetadata struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	StreamId      uint64                    `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	AuthInfo      *ssh.AllowResponse        `protobuf:"bytes,2,opt,name=auth_info,json=authInfo,proto3" json:"auth_info,omitempty"`
	PtyInfo       *ssh.SSHDownstreamPTYInfo `protobuf:"bytes,3,opt,name=pty_info,json=ptyInfo,proto3" json:"pty_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMetadata) Reset() {
	*x = StreamMetadata{}
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMetadata) ProtoMessage() {}

func (x *StreamMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMetadata.ProtoReflect.Descriptor instead.
func (*StreamMetadata) Descriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDescGZIP(), []int{3}
}

func (x *StreamMetadata) GetStreamId() uint64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *StreamMetadata) GetAuthInfo() *ssh.AllowResponse {
	if x != nil {
		return x.AuthInfo
	}
	return nil
}

func (x *StreamMetadata) GetPtyInfo() *ssh.SSHDownstreamPTYInfo {
	if x != nil {
		return x.PtyInfo
	}
	return nil
}

type StreamData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawData       []byte                 `protobuf:"bytes,1,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamData) Reset() {
	*x = StreamData{}
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamData) ProtoMessage() {}

func (x *StreamData) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamData.ProtoReflect.Descriptor instead.
func (*StreamData) Descriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDescGZIP(), []int{4}
}

func (x *StreamData) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

type StreamEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*StreamEvent_Resize
	Event         isStreamEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEvent) Reset() {
	*x = StreamEvent{}
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEvent) ProtoMessage() {}

func (x *StreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEvent.ProtoReflect.Descriptor instead.
func (*StreamEvent) Descriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDescGZIP(), []int{5}
}

func (x *StreamEvent) GetEvent() isStreamEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *StreamEvent) GetResize() *ResizeEvent {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isStreamEvent_Event interface {
	isStreamEvent_Event()
}

type StreamEvent_Resize struct {
	Resize *ResizeEvent `protobuf:"bytes,1,opt,name=resize,proto3,oneof"`
}

func (*StreamEvent_Resize) isStreamEvent_Event() {}

type PauseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Downstream    bool                   `protobuf:"varint,1,opt,name=downstream,proto3" json:"downstream,omitempty"`
	Upstream      bool                   `protobuf:"varint,2,opt,name=upstream,proto3" json:"upstream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRequest) Reset() {
	*x = PauseRequest{}
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRequest) ProtoMessage() {}

func (x *PauseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRequest.ProtoReflect.Descriptor instead.
func (*PauseRequest) Descriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDescGZIP(), []int{6}
}

func (x *PauseRequest) GetDownstream() bool {
	if x != nil {
		return x.Downstream
	}
	return false
}

func (x *PauseRequest) GetUpstream() bool {
	if x != nil {
		return x.Upstream
	}
	return false
}

type ResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Downstream    bool                   `protobuf:"varint,1,opt,name=downstream,proto3" json:"downstream,omitempty"`
	Upstream      bool                   `protobuf:"varint,2,opt,name=upstream,proto3" json:"upstream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDescGZIP(), []int{7}
}

func (x *ResumeRequest) GetDownstream() bool {
	if x != nil {
		return x.Downstream
	}
	return false
}

func (x *ResumeRequest) GetUpstream() bool {
	if x != nil {
		return x.Upstream
	}
	return false
}

type ResizeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidthColumns  uint32                 `protobuf:"varint,1,opt,name=width_columns,json=widthColumns,proto3" json:"width_columns,omitempty"`
	HeightRows    uint32                 `protobuf:"varint,2,opt,name=height_rows,json=heightRows,proto3" json:"height_rows,omitempty"`
	WidthPx       uint32                 `protobuf:"varint,3,opt,name=width_px,json=widthPx,proto3" json:"width_px,omitempty"`
	HeightPx      uint32                 `protobuf:"varint,4,opt,name=height_px,json=heightPx,proto3" json:"height_px,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeEvent) Reset() {
	*x = ResizeEvent{}
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeEvent) ProtoMessage() {}

func (x *ResizeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeEvent.ProtoReflect.Descriptor instead.
func (*ResizeEvent) Descriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDescGZIP(), []int{8}
}

func (x *ResizeEvent) GetWidthColumns() uint32 {
	if x != nil {
		return x.WidthColumns
	}
	return 0
}

func (x *ResizeEvent) GetHeightRows() uint32 {
	if x != nil {
		return x.HeightRows
	}
	return 0
}

func (x *ResizeEvent) GetWidthPx() uint32 {
	if x != nil {
		return x.WidthPx
	}
	return 0
}

func (x *ResizeEvent) GetHeightPx() uint32 {
	if x != nil {
		return x.HeightPx
	}
	return 0
}

type ReceiverServiceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	GrpcService   *v3.GrpcService        `protobuf:"bytes,2,opt,name=grpc_service,json=grpcService,proto3" json:"grpc_service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiverServiceConfig) Reset() {
	*x = ReceiverServiceConfig{}
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiverServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiverServiceConfig) ProtoMessage() {}

func (x *ReceiverServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiverServiceConfig.ProtoReflect.Descriptor instead.
func (*ReceiverServiceConfig) Descriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDescGZIP(), []int{9}
}

func (x *ReceiverServiceConfig) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ReceiverServiceConfig) GetGrpcService() *v3.GrpcService {
	if x != nil {
		return x.GrpcService
	}
	return nil
}

type ChannelFilterConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelFilterConfig) Reset() {
	*x = ChannelFilterConfig{}
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelFilterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelFilterConfig) ProtoMessage() {}

func (x *ChannelFilterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelFilterConfig.ProtoReflect.Descriptor instead.
func (*ChannelFilterConfig) Descriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDescGZIP(), []int{10}
}

type UpstreamTargetExtensionConfig struct {
	state                   protoimpl.MessageState                  `protogen:"open.v1"`
	ReceiverService         *v3.GrpcService                         `protobuf:"bytes,1,opt,name=receiver_service,json=receiverService,proto3" json:"receiver_service,omitempty"`
	ReceiverClusterEndpoint *UpstreamTargetExtensionConfig_Endpoint `protobuf:"bytes,2,opt,name=receiver_cluster_endpoint,json=receiverClusterEndpoint,proto3" json:"receiver_cluster_endpoint,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UpstreamTargetExtensionConfig) Reset() {
	*x = UpstreamTargetExtensionConfig{}
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamTargetExtensionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamTargetExtensionConfig) ProtoMessage() {}

func (x *UpstreamTargetExtensionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamTargetExtensionConfig.ProtoReflect.Descriptor instead.
func (*UpstreamTargetExtensionConfig) Descriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDescGZIP(), []int{11}
}

func (x *UpstreamTargetExtensionConfig) GetReceiverService() *v3.GrpcService {
	if x != nil {
		return x.ReceiverService
	}
	return nil
}

func (x *UpstreamTargetExtensionConfig) GetReceiverClusterEndpoint() *UpstreamTargetExtensionConfig_Endpoint {
	if x != nil {
		return x.ReceiverClusterEndpoint
	}
	return nil
}

type UpstreamTargetExtensionConfig_Endpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endpoint within the selected cluster to connect to
	Ip            string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamTargetExtensionConfig_Endpoint) Reset() {
	*x = UpstreamTargetExtensionConfig_Endpoint{}
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamTargetExtensionConfig_Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamTargetExtensionConfig_Endpoint) ProtoMessage() {}

func (x *UpstreamTargetExtensionConfig_Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamTargetExtensionConfig_Endpoint.ProtoReflect.Descriptor instead.
func (*UpstreamTargetExtensionConfig_Endpoint) Descriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDescGZIP(), []int{11, 0}
}

func (x *UpstreamTargetExtensionConfig_Endpoint) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *UpstreamTargetExtensionConfig_Endpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto protoreflect.FileDescriptor

const file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDesc = "" +
	"\n" +
	"@github.com/pomerium/envoy-custom/api/x/mirroring/mirroring.proto\x12\x14pomerium.x.mirroring\x1aMgithub.com/pomerium/envoy-custom/api/extensions/filters/network/ssh/ssh.proto\x1a'envoy/config/core/v3/grpc_service.proto\x1aAgithub.com/envoyproxy/protoc-gen-validate/validate/validate.proto\"\xd1\x01\n" +
	"\rMirrorRequest\x12B\n" +
	"\bmetadata\x18\x01 \x01(\v2$.pomerium.x.mirroring.StreamMetadataH\x00R\bmetadata\x126\n" +
	"\x04data\x18\x02 \x01(\v2 .pomerium.x.mirroring.StreamDataH\x00R\x04data\x129\n" +
	"\x05event\x18\x03 \x01(\v2!.pomerium.x.mirroring.StreamEventH\x00R\x05eventB\t\n" +
	"\arequest\"\xd4\x01\n" +
	"\x0eMirrorResponse\x12;\n" +
	"\x05hello\x18\x01 \x01(\v2#.pomerium.x.mirroring.ReceiverHelloH\x00R\x05hello\x12:\n" +
	"\x05pause\x18\x02 \x01(\v2\".pomerium.x.mirroring.PauseRequestH\x00R\x05pause\x12=\n" +
	"\x06resume\x18\x03 \x01(\v2#.pomerium.x.mirroring.ResumeRequestH\x00R\x06resumeB\n" +
	"\n" +
	"\bresponse\"\x0f\n" +
	"\rReceiverHello\"\xbc\x01\n" +
	"\x0eStreamMetadata\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\x04R\bstreamId\x12C\n" +
	"\tauth_info\x18\x02 \x01(\v2&.pomerium.extensions.ssh.AllowResponseR\bauthInfo\x12H\n" +
	"\bpty_info\x18\x03 \x01(\v2-.pomerium.extensions.ssh.SSHDownstreamPTYInfoR\aptyInfo\"'\n" +
	"\n" +
	"StreamData\x12\x19\n" +
	"\braw_data\x18\x01 \x01(\fR\arawData\"S\n" +
	"\vStreamEvent\x12;\n" +
	"\x06resize\x18\x01 \x01(\v2!.pomerium.x.mirroring.ResizeEventH\x00R\x06resizeB\a\n" +
	"\x05event\"J\n" +
	"\fPauseRequest\x12\x1e\n" +
	"\n" +
	"downstream\x18\x01 \x01(\bR\n" +
	"downstream\x12\x1a\n" +
	"\bupstream\x18\x02 \x01(\bR\bupstream\"K\n" +
	"\rResumeRequest\x12\x1e\n" +
	"\n" +
	"downstream\x18\x01 \x01(\bR\n" +
	"downstream\x12\x1a\n" +
	"\bupstream\x18\x02 \x01(\bR\bupstream\"\x8b\x01\n" +
	"\vResizeEvent\x12#\n" +
	"\rwidth_columns\x18\x01 \x01(\rR\fwidthColumns\x12\x1f\n" +
	"\vheight_rows\x18\x02 \x01(\rR\n" +
	"heightRows\x12\x19\n" +
	"\bwidth_px\x18\x03 \x01(\rR\awidthPx\x12\x1b\n" +
	"\theight_px\x18\x04 \x01(\rR\bheightPx\"y\n" +
	"\x15ReceiverServiceConfig\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12D\n" +
	"\fgrpc_service\x18\x02 \x01(\v2!.envoy.config.core.v3.GrpcServiceR\vgrpcService\"\x15\n" +
	"\x13ChannelFilterConfig\"\xb8\x02\n" +
	"\x1dUpstreamTargetExtensionConfig\x12L\n" +
	"\x10receiver_service\x18\x01 \x01(\v2!.envoy.config.core.v3.GrpcServiceR\x0freceiverService\x12\x82\x01\n" +
	"\x19receiver_cluster_endpoint\x18\x02 \x01(\v2<.pomerium.x.mirroring.UpstreamTargetExtensionConfig.EndpointB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x17receiverClusterEndpoint\x1aD\n" +
	"\bEndpoint\x12\x17\n" +
	"\x02ip\x18\x01 \x01(\tB\a\xfaB\x04r\x02p\x01R\x02ip\x12\x1f\n" +
	"\x04port\x18\x02 \x01(\rB\v\xfaB\b*\x06\x10\x80\x80\x04 \x00R\x04port2l\n" +
	"\x11MirroringReceiver\x12W\n" +
	"\x06Mirror\x12#.pomerium.x.mirroring.MirrorRequest\x1a$.pomerium.x.mirroring.MirrorResponse(\x010\x01B2Z0github.com/pomerium/envoy-custom/api/x/mirroringb\x06proto3"

var (
	file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDescOnce sync.Once
	file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDescData []byte
)

func file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDescGZIP() []byte {
	file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDescOnce.Do(func() {
		file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDesc), len(file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDesc)))
	})
	return file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDescData
}

var file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_goTypes = []any{
	(*MirrorRequest)(nil),                          // 0: pomerium.x.mirroring.MirrorRequest
	(*MirrorResponse)(nil),                         // 1: pomerium.x.mirroring.MirrorResponse
	(*ReceiverHello)(nil),                          // 2: pomerium.x.mirroring.ReceiverHello
	(*StreamMetadata)(nil),                         // 3: pomerium.x.mirroring.StreamMetadata
	(*StreamData)(nil),                             // 4: pomerium.x.mirroring.StreamData
	(*StreamEvent)(nil),                            // 5: pomerium.x.mirroring.StreamEvent
	(*PauseRequest)(nil),                           // 6: pomerium.x.mirroring.PauseRequest
	(*ResumeRequest)(nil),                          // 7: pomerium.x.mirroring.ResumeRequest
	(*ResizeEvent)(nil),                            // 8: pomerium.x.mirroring.ResizeEvent
	(*ReceiverServiceConfig)(nil),                  // 9: pomerium.x.mirroring.ReceiverServiceConfig
	(*ChannelFilterConfig)(nil),                    // 10: pomerium.x.mirroring.ChannelFilterConfig
	(*UpstreamTargetExtensionConfig)(nil),          // 11: pomerium.x.mirroring.UpstreamTargetExtensionConfig
	(*UpstreamTargetExtensionConfig_Endpoint)(nil), // 12: pomerium.x.mirroring.UpstreamTargetExtensionConfig.Endpoint
	(*ssh.AllowResponse)(nil),                      // 13: pomerium.extensions.ssh.AllowResponse
	(*ssh.SSHDownstreamPTYInfo)(nil),               // 14: pomerium.extensions.ssh.SSHDownstreamPTYInfo
	(*v3.GrpcService)(nil),                         // 15: envoy.config.core.v3.GrpcService
}
var file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_depIdxs = []int32{
	3,  // 0: pomerium.x.mirroring.MirrorRequest.metadata:type_name -> pomerium.x.mirroring.StreamMetadata
	4,  // 1: pomerium.x.mirroring.MirrorRequest.data:type_name -> pomerium.x.mirroring.StreamData
	5,  // 2: pomerium.x.mirroring.MirrorRequest.event:type_name -> pomerium.x.mirroring.StreamEvent
	2,  // 3: pomerium.x.mirroring.MirrorResponse.hello:type_name -> pomerium.x.mirroring.ReceiverHello
	6,  // 4: pomerium.x.mirroring.MirrorResponse.pause:type_name -> pomerium.x.mirroring.PauseRequest
	7,  // 5: pomerium.x.mirroring.MirrorResponse.resume:type_name -> pomerium.x.mirroring.ResumeRequest
	13, // 6: pomerium.x.mirroring.StreamMetadata.auth_info:type_name -> pomerium.extensions.ssh.AllowResponse
	14, // 7: pomerium.x.mirroring.StreamMetadata.pty_info:type_name -> pomerium.extensions.ssh.SSHDownstreamPTYInfo
	8,  // 8: pomerium.x.mirroring.StreamEvent.resize:type_name -> pomerium.x.mirroring.ResizeEvent
	15, // 9: pomerium.x.mirroring.ReceiverServiceConfig.grpc_service:type_name -> envoy.config.core.v3.GrpcService
	15, // 10: pomerium.x.mirroring.UpstreamTargetExtensionConfig.receiver_service:type_name -> envoy.config.core.v3.GrpcService
	12, // 11: pomerium.x.mirroring.UpstreamTargetExtensionConfig.receiver_cluster_endpoint:type_name -> pomerium.x.mirroring.UpstreamTargetExtensionConfig.Endpoint
	0,  // 12: pomerium.x.mirroring.MirroringReceiver.Mirror:input_type -> pomerium.x.mirroring.MirrorRequest
	1,  // 13: pomerium.x.mirroring.MirroringReceiver.Mirror:output_type -> pomerium.x.mirroring.MirrorResponse
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_init() }
func file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_init() {
	if File_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto != nil {
		return
	}
	file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[0].OneofWrappers = []any{
		(*MirrorRequest_Metadata)(nil),
		(*MirrorRequest_Data)(nil),
		(*MirrorRequest_Event)(nil),
	}
	file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[1].OneofWrappers = []any{
		(*MirrorResponse_Hello)(nil),
		(*MirrorResponse_Pause)(nil),
		(*MirrorResponse_Resume)(nil),
	}
	file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes[5].OneofWrappers = []any{
		(*StreamEvent_Resize)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDesc), len(file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_goTypes,
		DependencyIndexes: file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_depIdxs,
		MessageInfos:      file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_msgTypes,
	}.Build()
	File_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto = out.File
	file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_goTypes = nil
	file_github_com_pomerium_envoy_custom_api_x_mirroring_mirroring_proto_depIdxs = nil
}
