// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: github.com/pomerium/envoy-custom/api/x/mirroring/mirroring.proto

package mirroring

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MirroringReceiver_Mirror_FullMethodName = "/pomerium.x.mirroring.MirroringReceiver/Mirror"
)

// MirroringReceiverClient is the client API for MirroringReceiver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MirroringReceiverClient interface {
	Mirror(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MirrorRequest, MirrorResponse], error)
}

type mirroringReceiverClient struct {
	cc grpc.ClientConnInterface
}

func NewMirroringReceiverClient(cc grpc.ClientConnInterface) MirroringReceiverClient {
	return &mirroringReceiverClient{cc}
}

func (c *mirroringReceiverClient) Mirror(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MirrorRequest, MirrorResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MirroringReceiver_ServiceDesc.Streams[0], MirroringReceiver_Mirror_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MirrorRequest, MirrorResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MirroringReceiver_MirrorClient = grpc.BidiStreamingClient[MirrorRequest, MirrorResponse]

// MirroringReceiverServer is the server API for MirroringReceiver service.
// All implementations should embed UnimplementedMirroringReceiverServer
// for forward compatibility.
type MirroringReceiverServer interface {
	Mirror(grpc.BidiStreamingServer[MirrorRequest, MirrorResponse]) error
}

// UnimplementedMirroringReceiverServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMirroringReceiverServer struct{}

func (UnimplementedMirroringReceiverServer) Mirror(grpc.BidiStreamingServer[MirrorRequest, MirrorResponse]) error {
	return status.Error(codes.Unimplemented, "method Mirror not implemented")
}
func (UnimplementedMirroringReceiverServer) testEmbeddedByValue() {}

// UnsafeMirroringReceiverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MirroringReceiverServer will
// result in compilation errors.
type UnsafeMirroringReceiverServer interface {
	mustEmbedUnimplementedMirroringReceiverServer()
}

func RegisterMirroringReceiverServer(s grpc.ServiceRegistrar, srv MirroringReceiverServer) {
	// If the following call panics, it indicates UnimplementedMirroringReceiverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MirroringReceiver_ServiceDesc, srv)
}

func _MirroringReceiver_Mirror_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MirroringReceiverServer).Mirror(&grpc.GenericServerStream[MirrorRequest, MirrorResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MirroringReceiver_MirrorServer = grpc.BidiStreamingServer[MirrorRequest, MirrorResponse]

// MirroringReceiver_ServiceDesc is the grpc.ServiceDesc for MirroringReceiver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MirroringReceiver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pomerium.x.mirroring.MirroringReceiver",
	HandlerType: (*MirroringReceiverServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Mirror",
			Handler:       _MirroringReceiver_Mirror_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "github.com/pomerium/envoy-custom/api/x/mirroring/mirroring.proto",
}
