syntax = "proto3";

package pomerium.x.mirroring;

import "envoy/config/core/v3/grpc_service.proto";
import "google/protobuf/timestamp.proto";
import "validate/validate.proto";

option go_package = "github.com/pomerium/envoy-custom/api/x/mirroring";

// Warning: this API must maintain backwards compatibility. Do not renumber fields or embed messages
// from other packages that do not have compatibility requirements.
service MirroringReceiver {
  rpc Mirror(stream ClientMessage) returns (stream ServerMessage);
}

message ClientMessage {
  oneof msg {
    // ClientHello must be the first message sent on the stream immediately after it begins.
    ClientHello hello = 1;

    StreamData  data  = 2;
    StreamEvent event = 3;
  }
}

message ServerMessage {
  oneof msg {
    // ServerHello must be the first response received and must be sent by the server immediately
    // on connect. There is a 5 second timeout between the client starting the stream until the
    // ServerHello is received, or the session will be terminated.
    ServerHello hello = 1;

    PauseRequest  pause  = 2;
    ResumeRequest resume = 3;
  }
}

message ClientHello {
  // Client's API version. Starts at 1 and should be incremented if new features are added that
  // would require the client to know if the server supports them.
  uint32         api_version   = 1;
  string         envoy_version = 2; // opaque version string for logging/display purposes
  StreamMetadata metadata      = 3;
}

message ServerHello {
  // Server's API version. Must be <= client's version.
  uint32 api_version      = 1;
  string receiver_version = 2; // opaque version string for logging/display purposes

  // If true, the client should not resume the connection after receiving this message. The default
  // behavior is to pause both sides of the connection until the ServerHello is received, but the
  // server may choose to extend this pause. If so, the server must send a ResumeRequest manually.
  bool no_auto_resume = 3;
}

message StreamMetadata {
  string                    route_id                      = 1;
  google.protobuf.Timestamp start_time                    = 2;
  uint64                    stream_id                     = 3;
  string                    login_name                    = 4;
  string                    public_key_alg                = 5;
  bytes                     public_key_fingerprint_sha256 = 6;
  string                    session_id                    = 7;
  string                    user_id                       = 8;
  string                    session_binding_id            = 9;
  map<string, string>       access_request_metadata       = 10;
  string                    request_type                  = 11; // "shell" or "exec"
  string                    exec_command                  = 12; // if request_type is "exec"
  bool                      has_pty                       = 13;
  string                    term_env                      = 14;
  uint32                    width_columns                 = 15;
  uint32                    height_rows                   = 16;
  uint32                    width_px                      = 17;
  uint32                    height_px                     = 18;
  bytes                     term_modes                    = 19;
  bool                      downstream_paused             = 20;
  bool                      upstream_paused               = 21;
}

message StreamData {
  bytes raw_data = 1;
}

message StreamEvent {
  oneof event {
    ResizeEvent resize = 1;
  }
}

message PauseRequest {
  // Whether to pause the downstream half of the connection
  bool downstream = 1;
  // Whether to pause the upstream half of the connection
  bool upstream = 2;
}

message ResumeRequest {
  // Whether to resume the downstream half of the connection
  bool downstream = 1;
  // Whether to resume the upstream half of the connection
  bool upstream = 2;
}

message ResizeEvent {
  uint32 width_columns = 1;
  uint32 height_rows   = 2;
  uint32 width_px      = 3;
  uint32 height_px     = 4;
}

// This message is exempt from compatibility requirements.
message ReceiverServiceConfig {
  string                           hostname     = 1;
  envoy.config.core.v3.GrpcService grpc_service = 2;
}

// This message is exempt from compatibility requirements.
message ChannelFilterConfig {}

// This message is exempt from compatibility requirements.
message UpstreamTargetExtensionConfig {
  envoy.config.core.v3.GrpcService receiver_service = 1;

  message Endpoint {
    // Endpoint within the selected cluster to connect to
    string ip   = 1 [(validate.rules).string.ip = true];
    uint32 port = 2 [(validate.rules).uint32 = {
      gt: 0,
      lt: 65536,
    }];
  }
  Endpoint receiver_cluster_endpoint = 2 [(validate.rules).message.required = true];
}
