// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: github.com/pomerium/envoy-custom/api/extensions/health_check/event_sinks/grpc/event_sink.proto

package grpc

import (
	v3 "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
	v31 "github.com/envoyproxy/go-control-plane/envoy/data/core/v3"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrpcService   *v3.GrpcService        `protobuf:"bytes,4,opt,name=grpc_service,json=grpcService,proto3" json:"grpc_service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetGrpcService() *v3.GrpcService {
	if x != nil {
		return x.GrpcService
	}
	return nil
}

var File_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto protoreflect.FileDescriptor

const file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_rawDesc = "" +
	"\n" +
	"^github.com/pomerium/envoy-custom/api/extensions/health_check/event_sinks/grpc/event_sink.proto\x12.envoy.extensions.health_check.event_sinks.grpc\x1a'envoy/config/core/v3/grpc_service.proto\x1a+envoy/data/core/v3/health_check_event.proto\x1a\x1bgoogle/protobuf/empty.proto\x1aAgithub.com/envoyproxy/protoc-gen-validate/validate/validate.proto\"X\n" +
	"\x06Config\x12N\n" +
	"\fgrpc_service\x18\x04 \x01(\v2!.envoy.config.core.v3.GrpcServiceB\b\xfaB\x05\x8a\x01\x02\x10\x01R\vgrpcService2k\n" +
	"\x14HealthCheckEventSink\x12S\n" +
	"\x13LogHealthCheckEvent\x12$.envoy.data.core.v3.HealthCheckEvent\x1a\x16.google.protobuf.EmptyBOZMgithub.com/pomerium/envoy-custom/api/extensions/health_check/event_sinks/grpcb\x06proto3"

var (
	file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_rawDescOnce sync.Once
	file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_rawDescData []byte
)

func file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_rawDescGZIP() []byte {
	file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_rawDescOnce.Do(func() {
		file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_rawDesc), len(file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_rawDesc)))
	})
	return file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_rawDescData
}

var file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_goTypes = []any{
	(*Config)(nil),               // 0: envoy.extensions.health_check.event_sinks.grpc.Config
	(*v3.GrpcService)(nil),       // 1: envoy.config.core.v3.GrpcService
	(*v31.HealthCheckEvent)(nil), // 2: envoy.data.core.v3.HealthCheckEvent
	(*emptypb.Empty)(nil),        // 3: google.protobuf.Empty
}
var file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_depIdxs = []int32{
	1, // 0: envoy.extensions.health_check.event_sinks.grpc.Config.grpc_service:type_name -> envoy.config.core.v3.GrpcService
	2, // 1: envoy.extensions.health_check.event_sinks.grpc.HealthCheckEventSink.LogHealthCheckEvent:input_type -> envoy.data.core.v3.HealthCheckEvent
	3, // 2: envoy.extensions.health_check.event_sinks.grpc.HealthCheckEventSink.LogHealthCheckEvent:output_type -> google.protobuf.Empty
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() {
	file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_init()
}
func file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_init() {
	if File_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_rawDesc), len(file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_goTypes,
		DependencyIndexes: file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_depIdxs,
		MessageInfos:      file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_msgTypes,
	}.Build()
	File_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto = out.File
	file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_goTypes = nil
	file_github_com_pomerium_envoy_custom_api_extensions_health_check_event_sinks_grpc_event_sink_proto_depIdxs = nil
}
