// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: github.com/pomerium/envoy-custom/api/extensions/health_check/event_sinks/grpc/event_sink.proto

package grpc

import (
	context "context"
	v3 "github.com/envoyproxy/go-control-plane/envoy/data/core/v3"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HealthCheckEventSink_LogHealthCheckEvent_FullMethodName = "/envoy.extensions.health_check.event_sinks.grpc.HealthCheckEventSink/LogHealthCheckEvent"
)

// HealthCheckEventSinkClient is the client API for HealthCheckEventSink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthCheckEventSinkClient interface {
	LogHealthCheckEvent(ctx context.Context, in *v3.HealthCheckEvent, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type healthCheckEventSinkClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthCheckEventSinkClient(cc grpc.ClientConnInterface) HealthCheckEventSinkClient {
	return &healthCheckEventSinkClient{cc}
}

func (c *healthCheckEventSinkClient) LogHealthCheckEvent(ctx context.Context, in *v3.HealthCheckEvent, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HealthCheckEventSink_LogHealthCheckEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthCheckEventSinkServer is the server API for HealthCheckEventSink service.
// All implementations should embed UnimplementedHealthCheckEventSinkServer
// for forward compatibility.
type HealthCheckEventSinkServer interface {
	LogHealthCheckEvent(context.Context, *v3.HealthCheckEvent) (*emptypb.Empty, error)
}

// UnimplementedHealthCheckEventSinkServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthCheckEventSinkServer struct{}

func (UnimplementedHealthCheckEventSinkServer) LogHealthCheckEvent(context.Context, *v3.HealthCheckEvent) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LogHealthCheckEvent not implemented")
}
func (UnimplementedHealthCheckEventSinkServer) testEmbeddedByValue() {}

// UnsafeHealthCheckEventSinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthCheckEventSinkServer will
// result in compilation errors.
type UnsafeHealthCheckEventSinkServer interface {
	mustEmbedUnimplementedHealthCheckEventSinkServer()
}

func RegisterHealthCheckEventSinkServer(s grpc.ServiceRegistrar, srv HealthCheckEventSinkServer) {
	// If the following call panics, it indicates UnimplementedHealthCheckEventSinkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthCheckEventSink_ServiceDesc, srv)
}

func _HealthCheckEventSink_LogHealthCheckEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v3.HealthCheckEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthCheckEventSinkServer).LogHealthCheckEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthCheckEventSink_LogHealthCheckEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthCheckEventSinkServer).LogHealthCheckEvent(ctx, req.(*v3.HealthCheckEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthCheckEventSink_ServiceDesc is the grpc.ServiceDesc for HealthCheckEventSink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthCheckEventSink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "envoy.extensions.health_check.event_sinks.grpc.HealthCheckEventSink",
	HandlerType: (*HealthCheckEventSinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogHealthCheckEvent",
			Handler:    _HealthCheckEventSink_LogHealthCheckEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/pomerium/envoy-custom/api/extensions/health_check/event_sinks/grpc/event_sink.proto",
}
