load("//bazel:dynamic_extension.bzl", "cc_dynamic_extension")

package(default_visibility = ["//visibility:public"])

cc_dynamic_extension(
    name = "example_extension",
    srcs = [
        "extension.cc",
    ],
)
