// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v5.29.2
// source: api/extensions/filters/network/ssh/ssh.proto

package ssh

import (
	v3 "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_api_extensions_filters_network_ssh_ssh_proto_rawDescGZIP(), []int{0}
}

type CodecConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostKeys    []*HostKeyPair  `protobuf:"bytes,1,rep,name=host_keys,json=hostKeys,proto3" json:"host_keys,omitempty"`
	UserCaKey   *HostKeyPair    `protobuf:"bytes,2,opt,name=user_ca_key,json=userCaKey,proto3" json:"user_ca_key,omitempty"`
	GrpcService *v3.GrpcService `protobuf:"bytes,3,opt,name=grpc_service,json=grpcService,proto3" json:"grpc_service,omitempty"`
}

func (x *CodecConfig) Reset() {
	*x = CodecConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodecConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodecConfig) ProtoMessage() {}

func (x *CodecConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodecConfig.ProtoReflect.Descriptor instead.
func (*CodecConfig) Descriptor() ([]byte, []int) {
	return file_api_extensions_filters_network_ssh_ssh_proto_rawDescGZIP(), []int{1}
}

func (x *CodecConfig) GetHostKeys() []*HostKeyPair {
	if x != nil {
		return x.HostKeys
	}
	return nil
}

func (x *CodecConfig) GetUserCaKey() *HostKeyPair {
	if x != nil {
		return x.UserCaKey
	}
	return nil
}

func (x *CodecConfig) GetGrpcService() *v3.GrpcService {
	if x != nil {
		return x.GrpcService
	}
	return nil
}

type HostKeyPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKeyFile  string `protobuf:"bytes,1,opt,name=public_key_file,json=publicKeyFile,proto3" json:"public_key_file,omitempty"`
	PrivateKeyFile string `protobuf:"bytes,2,opt,name=private_key_file,json=privateKeyFile,proto3" json:"private_key_file,omitempty"`
}

func (x *HostKeyPair) Reset() {
	*x = HostKeyPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostKeyPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostKeyPair) ProtoMessage() {}

func (x *HostKeyPair) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostKeyPair.ProtoReflect.Descriptor instead.
func (*HostKeyPair) Descriptor() ([]byte, []int) {
	return file_api_extensions_filters_network_ssh_ssh_proto_rawDescGZIP(), []int{2}
}

func (x *HostKeyPair) GetPublicKeyFile() string {
	if x != nil {
		return x.PublicKeyFile
	}
	return ""
}

func (x *HostKeyPair) GetPrivateKeyFile() string {
	if x != nil {
		return x.PrivateKeyFile
	}
	return ""
}

type AuthenticationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username      string     `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	AuthMethod    string     `protobuf:"bytes,2,opt,name=auth_method,json=authMethod,proto3" json:"auth_method,omitempty"`
	Hostname      string     `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	MethodRequest *anypb.Any `protobuf:"bytes,4,opt,name=method_request,json=methodRequest,proto3" json:"method_request,omitempty"`
}

func (x *AuthenticationRequest) Reset() {
	*x = AuthenticationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationRequest) ProtoMessage() {}

func (x *AuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationRequest.ProtoReflect.Descriptor instead.
func (*AuthenticationRequest) Descriptor() ([]byte, []int) {
	return file_api_extensions_filters_network_ssh_ssh_proto_rawDescGZIP(), []int{3}
}

func (x *AuthenticationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticationRequest) GetAuthMethod() string {
	if x != nil {
		return x.AuthMethod
	}
	return ""
}

func (x *AuthenticationRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AuthenticationRequest) GetMethodRequest() *anypb.Any {
	if x != nil {
		return x.MethodRequest
	}
	return nil
}

type PublicKeyMethodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey    []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PublicKeyAlg string `protobuf:"bytes,2,opt,name=public_key_alg,json=publicKeyAlg,proto3" json:"public_key_alg,omitempty"`
}

func (x *PublicKeyMethodRequest) Reset() {
	*x = PublicKeyMethodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicKeyMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyMethodRequest) ProtoMessage() {}

func (x *PublicKeyMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyMethodRequest.ProtoReflect.Descriptor instead.
func (*PublicKeyMethodRequest) Descriptor() ([]byte, []int) {
	return file_api_extensions_filters_network_ssh_ssh_proto_rawDescGZIP(), []int{4}
}

func (x *PublicKeyMethodRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *PublicKeyMethodRequest) GetPublicKeyAlg() string {
	if x != nil {
		return x.PublicKeyAlg
	}
	return ""
}

type KeyboardInteractiveMethodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Submethods []string `protobuf:"bytes,1,rep,name=submethods,proto3" json:"submethods,omitempty"`
}

func (x *KeyboardInteractiveMethodRequest) Reset() {
	*x = KeyboardInteractiveMethodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyboardInteractiveMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardInteractiveMethodRequest) ProtoMessage() {}

func (x *KeyboardInteractiveMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardInteractiveMethodRequest.ProtoReflect.Descriptor instead.
func (*KeyboardInteractiveMethodRequest) Descriptor() ([]byte, []int) {
	return file_api_extensions_filters_network_ssh_ssh_proto_rawDescGZIP(), []int{5}
}

func (x *KeyboardInteractiveMethodRequest) GetSubmethods() []string {
	if x != nil {
		return x.Submethods
	}
	return nil
}

type KeyboardInteractiveInfoPrompts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string                                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Instruction string                                   `protobuf:"bytes,2,opt,name=instruction,proto3" json:"instruction,omitempty"`
	LanguageTag string                                   `protobuf:"bytes,3,opt,name=language_tag,json=languageTag,proto3" json:"language_tag,omitempty"`
	Prompts     []*KeyboardInteractiveInfoPrompts_Prompt `protobuf:"bytes,4,rep,name=prompts,proto3" json:"prompts,omitempty"`
}

func (x *KeyboardInteractiveInfoPrompts) Reset() {
	*x = KeyboardInteractiveInfoPrompts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyboardInteractiveInfoPrompts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardInteractiveInfoPrompts) ProtoMessage() {}

func (x *KeyboardInteractiveInfoPrompts) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardInteractiveInfoPrompts.ProtoReflect.Descriptor instead.
func (*KeyboardInteractiveInfoPrompts) Descriptor() ([]byte, []int) {
	return file_api_extensions_filters_network_ssh_ssh_proto_rawDescGZIP(), []int{6}
}

func (x *KeyboardInteractiveInfoPrompts) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeyboardInteractiveInfoPrompts) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *KeyboardInteractiveInfoPrompts) GetLanguageTag() string {
	if x != nil {
		return x.LanguageTag
	}
	return ""
}

func (x *KeyboardInteractiveInfoPrompts) GetPrompts() []*KeyboardInteractiveInfoPrompts_Prompt {
	if x != nil {
		return x.Prompts
	}
	return nil
}

type KeyboardInteractiveInfoPromptResponses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses []string `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
}

func (x *KeyboardInteractiveInfoPromptResponses) Reset() {
	*x = KeyboardInteractiveInfoPromptResponses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyboardInteractiveInfoPromptResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardInteractiveInfoPromptResponses) ProtoMessage() {}

func (x *KeyboardInteractiveInfoPromptResponses) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardInteractiveInfoPromptResponses.ProtoReflect.Descriptor instead.
func (*KeyboardInteractiveInfoPromptResponses) Descriptor() ([]byte, []int) {
	return file_api_extensions_filters_network_ssh_ssh_proto_rawDescGZIP(), []int{7}
}

func (x *KeyboardInteractiveInfoPromptResponses) GetResponses() []string {
	if x != nil {
		return x.Responses
	}
	return nil
}

type ClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*ClientMessage_Event
	//	*ClientMessage_AuthRequest
	//	*ClientMessage_InfoResponse
	Message isClientMessage_Message `protobuf_oneof:"message"`
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_api_extensions_filters_network_ssh_ssh_proto_rawDescGZIP(), []int{8}
}

func (m *ClientMessage) GetMessage() isClientMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ClientMessage) GetEvent() *StreamEvent {
	if x, ok := x.GetMessage().(*ClientMessage_Event); ok {
		return x.Event
	}
	return nil
}

func (x *ClientMessage) GetAuthRequest() *AuthenticationRequest {
	if x, ok := x.GetMessage().(*ClientMessage_AuthRequest); ok {
		return x.AuthRequest
	}
	return nil
}

func (x *ClientMessage) GetInfoResponse() *InfoResponse {
	if x, ok := x.GetMessage().(*ClientMessage_InfoResponse); ok {
		return x.InfoResponse
	}
	return nil
}

type isClientMessage_Message interface {
	isClientMessage_Message()
}

type ClientMessage_Event struct {
	Event *StreamEvent `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type ClientMessage_AuthRequest struct {
	AuthRequest *AuthenticationRequest `protobuf:"bytes,2,opt,name=auth_request,json=authRequest,proto3,oneof"`
}

type ClientMessage_InfoResponse struct {
	InfoResponse *InfoResponse `protobuf:"bytes,3,opt,name=info_response,json=infoResponse,proto3,oneof"`
}

func (*ClientMessage_Event) isClientMessage_Message() {}

func (*ClientMessage_AuthRequest) isClientMessage_Message() {}

func (*ClientMessage_InfoResponse) isClientMessage_Message() {}

type StreamEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*StreamEvent_DownstreamConnected
	Event isStreamEvent_Event `protobuf_oneof:"event"`
}

func (x *StreamEvent) Reset() {
	*x = StreamEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEvent) ProtoMessage() {}

func (x *StreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEvent.ProtoReflect.Descriptor instead.
func (*StreamEvent) Descriptor() ([]byte, []int) {
	return file_api_extensions_filters_network_ssh_ssh_proto_rawDescGZIP(), []int{9}
}

func (m *StreamEvent) GetEvent() isStreamEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *StreamEvent) GetDownstreamConnected() *DownstreamConnectEvent {
	if x, ok := x.GetEvent().(*StreamEvent_DownstreamConnected); ok {
		return x.DownstreamConnected
	}
	return nil
}

type isStreamEvent_Event interface {
	isStreamEvent_Event()
}

type StreamEvent_DownstreamConnected struct {
	DownstreamConnected *DownstreamConnectEvent `protobuf:"bytes,1,opt,name=downstream_connected,json=downstreamConnected,proto3,oneof"`
}

func (*StreamEvent_DownstreamConnected) isStreamEvent_Event() {}

type DownstreamConnectEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DownstreamConnectEvent) Reset() {
	*x = DownstreamConnectEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownstreamConnectEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownstreamConnectEvent) ProtoMessage() {}

func (x *DownstreamConnectEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownstreamConnectEvent.ProtoReflect.Descriptor instead.
func (*DownstreamConnectEvent) Descriptor() ([]byte, []int) {
	return file_api_extensions_filters_network_ssh_ssh_proto_rawDescGZIP(), []int{10}
}

type ServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*ServerMessage_AuthResponse
	//	*ServerMessage_ControlRequest
	Message isServerMessage_Message `protobuf_oneof:"message"`
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_api_extensions_filters_network_ssh_ssh_proto_rawDescGZIP(), []int{11}
}

func (m *ServerMessage) GetMessage() isServerMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ServerMessage) GetAuthResponse() *AuthenticationResponse {
	if x, ok := x.GetMessage().(*ServerMessage_AuthResponse); ok {
		return x.AuthResponse
	}
	return nil
}

func (x *ServerMessage) GetControlRequest() *ControlRequest {
	if x, ok := x.GetMessage().(*ServerMessage_ControlRequest); ok {
		return x.ControlRequest
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_AuthResponse struct {
	AuthResponse *AuthenticationResponse `protobuf:"bytes,1,opt,name=auth_response,json=authResponse,proto3,oneof"`
}

type ServerMessage_ControlRequest struct {
	ControlRequest *ControlRequest `protobuf:"bytes,2,opt,name=control_request,json=controlRequest,proto3,oneof"`
}

func (*ServerMessage_AuthResponse) isServerMessage_Message() {}

func (*ServerMessage_ControlRequest) isServerMessage_Message() {}

type AuthenticationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*AuthenticationResponse_Allow
	//	*AuthenticationResponse_Deny
	//	*AuthenticationResponse_InfoRequest
	Response isAuthenticationResponse_Response `protobuf_oneof:"response"`
}

func (x *AuthenticationResponse) Reset() {
	*x = AuthenticationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationResponse) ProtoMessage() {}

func (x *AuthenticationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationResponse.ProtoReflect.Descriptor instead.
func (*AuthenticationResponse) Descriptor() ([]byte, []int) {
	return file_api_extensions_filters_network_ssh_ssh_proto_rawDescGZIP(), []int{12}
}

func (m *AuthenticationResponse) GetResponse() isAuthenticationResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *AuthenticationResponse) GetAllow() *AllowResponse {
	if x, ok := x.GetResponse().(*AuthenticationResponse_Allow); ok {
		return x.Allow
	}
	return nil
}

func (x *AuthenticationResponse) GetDeny() *DenyResponse {
	if x, ok := x.GetResponse().(*AuthenticationResponse_Deny); ok {
		return x.Deny
	}
	return nil
}

func (x *AuthenticationResponse) GetInfoRequest() *InfoRequest {
	if x, ok := x.GetResponse().(*AuthenticationResponse_InfoRequest); ok {
		return x.InfoRequest
	}
	return nil
}

type isAuthenticationResponse_Response interface {
	isAuthenticationResponse_Response()
}

type AuthenticationResponse_Allow struct {
	Allow *AllowResponse `protobuf:"bytes,1,opt,name=allow,proto3,oneof"`
}

type AuthenticationResponse_Deny struct {
	Deny *DenyResponse `protobuf:"bytes,2,opt,name=deny,proto3,oneof"`
}

type AuthenticationResponse_InfoRequest struct {
	InfoRequest *InfoRequest `protobuf:"bytes,3,opt,name=info_request,json=infoRequest,proto3,oneof"`
}

func (*AuthenticationResponse_Allow) isAuthenticationResponse_Response() {}

func (*AuthenticationResponse_Deny) isAuthenticationResponse_Response() {}

func (*AuthenticationResponse_InfoRequest) isAuthenticationResponse_Response() {}

type ControlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Action:
	//
	//	*ControlRequest_CloseStream_
	Action isControlRequest_Action `protobuf_oneof:"action"`
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_api_extensions_filters_network_ssh_ssh_proto_rawDescGZIP(), []int{13}
}

func (m *ControlRequest) GetAction() isControlRequest_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *ControlRequest) GetCloseStream() *ControlRequest_CloseStream {
	if x, ok := x.GetAction().(*ControlRequest_CloseStream_); ok {
		return x.CloseStream
	}
	return nil
}

type isControlRequest_Action interface {
	isControlRequest_Action()
}

type ControlRequest_CloseStream_ struct {
	CloseStream *ControlRequest_CloseStream `protobuf:"bytes,1,opt,name=close_stream,json=closeStream,proto3,oneof"`
}

func (*ControlRequest_CloseStream_) isControlRequest_Action() {}

type AllowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username             string       `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	MethodsAuthenticated []string     `protobuf:"bytes,2,rep,name=methods_authenticated,json=methodsAuthenticated,proto3" json:"methods_authenticated,omitempty"`
	Hostname             string       `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	PublicKey            []byte       `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Permissions          *Permissions `protobuf:"bytes,5,opt,name=permissions,proto3" json:"permissions,omitempty"`
}

func (x *AllowResponse) Reset() {
	*x = AllowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowResponse) ProtoMessage() {}

func (x *AllowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowResponse.ProtoReflect.Descriptor instead.
func (*AllowResponse) Descriptor() ([]byte, []int) {
	return file_api_extensions_filters_network_ssh_ssh_proto_rawDescGZIP(), []int{14}
}

func (x *AllowResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AllowResponse) GetMethodsAuthenticated() []string {
	if x != nil {
		return x.MethodsAuthenticated
	}
	return nil
}

func (x *AllowResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AllowResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *AllowResponse) GetPermissions() *Permissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type Permissions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PermitPortForwarding  bool                   `protobuf:"varint,1,opt,name=permit_port_forwarding,json=permitPortForwarding,proto3" json:"permit_port_forwarding,omitempty"`
	PermitAgentForwarding bool                   `protobuf:"varint,2,opt,name=permit_agent_forwarding,json=permitAgentForwarding,proto3" json:"permit_agent_forwarding,omitempty"`
	PermitX11Forwarding   bool                   `protobuf:"varint,3,opt,name=permit_x11_forwarding,json=permitX11Forwarding,proto3" json:"permit_x11_forwarding,omitempty"`
	PermitPty             bool                   `protobuf:"varint,4,opt,name=permit_pty,json=permitPty,proto3" json:"permit_pty,omitempty"`
	PermitUserRc          bool                   `protobuf:"varint,5,opt,name=permit_user_rc,json=permitUserRc,proto3" json:"permit_user_rc,omitempty"`
	ValidBefore           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=valid_before,json=validBefore,proto3" json:"valid_before,omitempty"`
	ValidAfter            *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=valid_after,json=validAfter,proto3" json:"valid_after,omitempty"`
	PermitOpen            []string               `protobuf:"bytes,8,rep,name=permit_open,json=permitOpen,proto3" json:"permit_open,omitempty"`
	PermitListen          []string               `protobuf:"bytes,9,rep,name=permit_listen,json=permitListen,proto3" json:"permit_listen,omitempty"`
	ForceCommand          *string                `protobuf:"bytes,10,opt,name=force_command,json=forceCommand,proto3,oneof" json:"force_command,omitempty"`
	ForceEnv              map[string]string      `protobuf:"bytes,11,rep,name=force_env,json=forceEnv,proto3" json:"force_env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RequireUserPresence   *bool                  `protobuf:"varint,12,opt,name=require_user_presence,json=requireUserPresence,proto3,oneof" json:"require_user_presence,omitempty"`
	RequireVerify         *bool                  `protobuf:"varint,13,opt,name=require_verify,json=requireVerify,proto3,oneof" json:"require_verify,omitempty"`
}

func (x *Permissions) Reset() {
	*x = Permissions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Permissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permissions) ProtoMessage() {}

func (x *Permissions) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permissions.ProtoReflect.Descriptor instead.
func (*Permissions) Descriptor() ([]byte, []int) {
	return file_api_extensions_filters_network_ssh_ssh_proto_rawDescGZIP(), []int{15}
}

func (x *Permissions) GetPermitPortForwarding() bool {
	if x != nil {
		return x.PermitPortForwarding
	}
	return false
}

func (x *Permissions) GetPermitAgentForwarding() bool {
	if x != nil {
		return x.PermitAgentForwarding
	}
	return false
}

func (x *Permissions) GetPermitX11Forwarding() bool {
	if x != nil {
		return x.PermitX11Forwarding
	}
	return false
}

func (x *Permissions) GetPermitPty() bool {
	if x != nil {
		return x.PermitPty
	}
	return false
}

func (x *Permissions) GetPermitUserRc() bool {
	if x != nil {
		return x.PermitUserRc
	}
	return false
}

func (x *Permissions) GetValidBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidBefore
	}
	return nil
}

func (x *Permissions) GetValidAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidAfter
	}
	return nil
}

func (x *Permissions) GetPermitOpen() []string {
	if x != nil {
		return x.PermitOpen
	}
	return nil
}

func (x *Permissions) GetPermitListen() []string {
	if x != nil {
		return x.PermitListen
	}
	return nil
}

func (x *Permissions) GetForceCommand() string {
	if x != nil && x.ForceCommand != nil {
		return *x.ForceCommand
	}
	return ""
}

func (x *Permissions) GetForceEnv() map[string]string {
	if x != nil {
		return x.ForceEnv
	}
	return nil
}

func (x *Permissions) GetRequireUserPresence() bool {
	if x != nil && x.RequireUserPresence != nil {
		return *x.RequireUserPresence
	}
	return false
}

func (x *Permissions) GetRequireVerify() bool {
	if x != nil && x.RequireVerify != nil {
		return *x.RequireVerify
	}
	return false
}

type DenyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Partial bool     `protobuf:"varint,1,opt,name=partial,proto3" json:"partial,omitempty"`
	Methods []string `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (x *DenyResponse) Reset() {
	*x = DenyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DenyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyResponse) ProtoMessage() {}

func (x *DenyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyResponse.ProtoReflect.Descriptor instead.
func (*DenyResponse) Descriptor() ([]byte, []int) {
	return file_api_extensions_filters_network_ssh_ssh_proto_rawDescGZIP(), []int{16}
}

func (x *DenyResponse) GetPartial() bool {
	if x != nil {
		return x.Partial
	}
	return false
}

func (x *DenyResponse) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type InfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method  string     `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Request *anypb.Any `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_api_extensions_filters_network_ssh_ssh_proto_rawDescGZIP(), []int{17}
}

func (x *InfoRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InfoRequest) GetRequest() *anypb.Any {
	if x != nil {
		return x.Request
	}
	return nil
}

type InfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method   string     `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Response *anypb.Any `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_api_extensions_filters_network_ssh_ssh_proto_rawDescGZIP(), []int{18}
}

func (x *InfoResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InfoResponse) GetResponse() *anypb.Any {
	if x != nil {
		return x.Response
	}
	return nil
}

type KeyboardInteractiveInfoPrompts_Prompt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Echo   bool   `protobuf:"varint,2,opt,name=echo,proto3" json:"echo,omitempty"`
}

func (x *KeyboardInteractiveInfoPrompts_Prompt) Reset() {
	*x = KeyboardInteractiveInfoPrompts_Prompt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyboardInteractiveInfoPrompts_Prompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardInteractiveInfoPrompts_Prompt) ProtoMessage() {}

func (x *KeyboardInteractiveInfoPrompts_Prompt) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardInteractiveInfoPrompts_Prompt.ProtoReflect.Descriptor instead.
func (*KeyboardInteractiveInfoPrompts_Prompt) Descriptor() ([]byte, []int) {
	return file_api_extensions_filters_network_ssh_ssh_proto_rawDescGZIP(), []int{6, 0}
}

func (x *KeyboardInteractiveInfoPrompts_Prompt) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *KeyboardInteractiveInfoPrompts_Prompt) GetEcho() bool {
	if x != nil {
		return x.Echo
	}
	return false
}

type ControlRequest_CloseStream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason *string `protobuf:"bytes,1,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
}

func (x *ControlRequest_CloseStream) Reset() {
	*x = ControlRequest_CloseStream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlRequest_CloseStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest_CloseStream) ProtoMessage() {}

func (x *ControlRequest_CloseStream) ProtoReflect() protoreflect.Message {
	mi := &file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest_CloseStream.ProtoReflect.Descriptor instead.
func (*ControlRequest_CloseStream) Descriptor() ([]byte, []int) {
	return file_api_extensions_filters_network_ssh_ssh_proto_rawDescGZIP(), []int{13, 0}
}

func (x *ControlRequest_CloseStream) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

var File_api_extensions_filters_network_ssh_ssh_proto protoreflect.FileDescriptor

var file_api_extensions_filters_network_ssh_ssh_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2f, 0x73, 0x73, 0x68, 0x2f, 0x73, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17,
	0x70, 0x6f, 0x6d, 0x65, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x73, 0x73, 0x68, 0x1a, 0x27, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2f, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x33, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x08, 0x0a, 0x06,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0xdc, 0x01, 0x0a, 0x0b, 0x43, 0x6f, 0x64, 0x65, 0x63,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x41, 0x0a, 0x09, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6b,
	0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x6f, 0x6d, 0x65,
	0x72, 0x69, 0x75, 0x6d, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x73, 0x73, 0x68, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x52,
	0x08, 0x68, 0x6f, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x44, 0x0a, 0x0b, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x63, 0x61, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x70, 0x6f, 0x6d, 0x65, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x73, 0x73, 0x68, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x4b, 0x65, 0x79,
	0x50, 0x61, 0x69, 0x72, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x43, 0x61, 0x4b, 0x65, 0x79, 0x12,
	0x44, 0x0a, 0x0c, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x33, 0x2e, 0x47, 0x72, 0x70,
	0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x0b, 0x67, 0x72, 0x70, 0x63, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x5f, 0x0a, 0x0b, 0x48, 0x6f, 0x73, 0x74, 0x4b, 0x65, 0x79,
	0x50, 0x61, 0x69, 0x72, 0x12, 0x26, 0x0a, 0x0f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b,
	0x65, 0x79, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x28, 0x0a, 0x10,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x66, 0x69, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x22, 0xad, 0x01, 0x0a, 0x15, 0x41, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x61, 0x75, 0x74, 0x68, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0e, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x0d, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5d, 0x0a, 0x16, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12,
	0x24, 0x0a, 0x0e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x61, 0x6c,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x41, 0x6c, 0x67, 0x22, 0x42, 0x0a, 0x20, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x62,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x73,
	0x75, 0x62, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x22, 0x89, 0x02, 0x0a, 0x1e, 0x4b, 0x65,
	0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x5f, 0x74,
	0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x54, 0x61, 0x67, 0x12, 0x58, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3e, 0x2e, 0x70, 0x6f, 0x6d, 0x65, 0x72, 0x69, 0x75,
	0x6d, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x73, 0x73, 0x68,
	0x2e, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x73, 0x2e,
	0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x73, 0x1a,
	0x34, 0x0a, 0x06, 0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f,
	0x6d, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x63, 0x68, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x65, 0x63, 0x68, 0x6f, 0x22, 0x46, 0x0a, 0x26, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x50, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22, 0xfb, 0x01,
	0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x3c, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x70, 0x6f, 0x6d, 0x65, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x73, 0x73, 0x68, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x53, 0x0a,
	0x0c, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x70, 0x6f, 0x6d, 0x65, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x65,
	0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x73, 0x73, 0x68, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x4c, 0x0a, 0x0d, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x6f, 0x6d, 0x65,
	0x72, 0x69, 0x75, 0x6d, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x73, 0x73, 0x68, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x0c, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x7c, 0x0a, 0x0b, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x64, 0x0a, 0x14, 0x64, 0x6f,
	0x77, 0x6e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x70, 0x6f, 0x6d, 0x65, 0x72,
	0x69, 0x75, 0x6d, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x73,
	0x73, 0x68, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x13, 0x64, 0x6f, 0x77,
	0x6e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x6f, 0x77,
	0x6e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x22, 0xc6, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x56, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x70,
	0x6f, 0x6d, 0x65, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x73, 0x73, 0x68, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52,
	0x0c, 0x61, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a,
	0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x70, 0x6f, 0x6d, 0x65, 0x72, 0x69, 0x75,
	0x6d, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x73, 0x73, 0x68,
	0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xec, 0x01, 0x0a,
	0x16, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x05, 0x61, 0x6c, 0x6c, 0x6f, 0x77,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x6f, 0x6d, 0x65, 0x72, 0x69, 0x75,
	0x6d, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x73, 0x73, 0x68,
	0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00,
	0x52, 0x05, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x3b, 0x0a, 0x04, 0x64, 0x65, 0x6e, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x6f, 0x6d, 0x65, 0x72, 0x69, 0x75, 0x6d,
	0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x73, 0x73, 0x68, 0x2e,
	0x44, 0x65, 0x6e, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x04,
	0x64, 0x65, 0x6e, 0x79, 0x12, 0x49, 0x0a, 0x0c, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x6f, 0x6d,
	0x65, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x73, 0x73, 0x68, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x0b, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42,
	0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xab, 0x01, 0x0a, 0x0e,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x58,
	0x0a, 0x0c, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x70, 0x6f, 0x6d, 0x65, 0x72, 0x69, 0x75, 0x6d, 0x2e,
	0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x73, 0x73, 0x68, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x6c, 0x6f,
	0x73, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x1a, 0x35, 0x0a, 0x0b, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1b, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x42,
	0x08, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xe3, 0x01, 0x0a, 0x0d, 0x41, 0x6c,
	0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x15, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x73, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x14, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x41,
	0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x46, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70,
	0x6f, 0x6d, 0x65, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x73, 0x73, 0x68, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x92, 0x06, 0x0a, 0x0b, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x34, 0x0a, 0x16, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x66,
	0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x14, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61,
	0x72, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x36, 0x0a, 0x17, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x5f,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x15, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x32, 0x0a,
	0x15, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x5f, 0x78, 0x31, 0x31, 0x5f, 0x66, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x70, 0x65,
	0x72, 0x6d, 0x69, 0x74, 0x58, 0x31, 0x31, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x69, 0x6e,
	0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x5f, 0x70, 0x74, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x50, 0x74, 0x79,
	0x12, 0x24, 0x0a, 0x0e, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x72, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x63, 0x12, 0x3d, 0x0a, 0x0c, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f,
	0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x42,
	0x65, 0x66, 0x6f, 0x72, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x61,
	0x66, 0x74, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x41, 0x66, 0x74,
	0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x5f, 0x6f, 0x70, 0x65,
	0x6e, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x4f,
	0x70, 0x65, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x12, 0x28, 0x0a, 0x0d, 0x66, 0x6f, 0x72, 0x63,
	0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x0c, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x4f, 0x0a, 0x09, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x5f, 0x65, 0x6e, 0x76, 0x18,
	0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x70, 0x6f, 0x6d, 0x65, 0x72, 0x69, 0x75, 0x6d,
	0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x73, 0x73, 0x68, 0x2e,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x46, 0x6f, 0x72, 0x63,
	0x65, 0x45, 0x6e, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x66, 0x6f, 0x72, 0x63, 0x65,
	0x45, 0x6e, 0x76, 0x12, 0x37, 0x0a, 0x15, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x08, 0x48, 0x01, 0x52, 0x13, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x88, 0x01, 0x01, 0x12, 0x2a, 0x0a, 0x0e,
	0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x08, 0x48, 0x02, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x88, 0x01, 0x01, 0x1a, 0x3b, 0x0a, 0x0d, 0x46, 0x6f, 0x72, 0x63,
	0x65, 0x45, 0x6e, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x42, 0x18, 0x0a, 0x16, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63,
	0x65, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x5f, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x22, 0x42, 0x0a, 0x0c, 0x44, 0x65, 0x6e, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x22, 0x55, 0x0a, 0x0b, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12,
	0x2e, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x58, 0x0a, 0x0c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x30, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x76, 0x0a, 0x10, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x62, 0x0a,
	0x0c, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x26, 0x2e,
	0x70, 0x6f, 0x6d, 0x65, 0x72, 0x69, 0x75, 0x6d, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x73, 0x73, 0x68, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x26, 0x2e, 0x70, 0x6f, 0x6d, 0x65, 0x72, 0x69, 0x75, 0x6d,
	0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x73, 0x73, 0x68, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x28, 0x01, 0x30,
	0x01, 0x42, 0x45, 0x5a, 0x43, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x70, 0x6f, 0x6d, 0x65, 0x72, 0x69, 0x75, 0x6d, 0x2f, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2d, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x73, 0x73, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_extensions_filters_network_ssh_ssh_proto_rawDescOnce sync.Once
	file_api_extensions_filters_network_ssh_ssh_proto_rawDescData = file_api_extensions_filters_network_ssh_ssh_proto_rawDesc
)

func file_api_extensions_filters_network_ssh_ssh_proto_rawDescGZIP() []byte {
	file_api_extensions_filters_network_ssh_ssh_proto_rawDescOnce.Do(func() {
		file_api_extensions_filters_network_ssh_ssh_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_extensions_filters_network_ssh_ssh_proto_rawDescData)
	})
	return file_api_extensions_filters_network_ssh_ssh_proto_rawDescData
}

var file_api_extensions_filters_network_ssh_ssh_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_extensions_filters_network_ssh_ssh_proto_goTypes = []interface{}{
	(*Config)(nil),                                 // 0: pomerium.extensions.ssh.Config
	(*CodecConfig)(nil),                            // 1: pomerium.extensions.ssh.CodecConfig
	(*HostKeyPair)(nil),                            // 2: pomerium.extensions.ssh.HostKeyPair
	(*AuthenticationRequest)(nil),                  // 3: pomerium.extensions.ssh.AuthenticationRequest
	(*PublicKeyMethodRequest)(nil),                 // 4: pomerium.extensions.ssh.PublicKeyMethodRequest
	(*KeyboardInteractiveMethodRequest)(nil),       // 5: pomerium.extensions.ssh.KeyboardInteractiveMethodRequest
	(*KeyboardInteractiveInfoPrompts)(nil),         // 6: pomerium.extensions.ssh.KeyboardInteractiveInfoPrompts
	(*KeyboardInteractiveInfoPromptResponses)(nil), // 7: pomerium.extensions.ssh.KeyboardInteractiveInfoPromptResponses
	(*ClientMessage)(nil),                          // 8: pomerium.extensions.ssh.ClientMessage
	(*StreamEvent)(nil),                            // 9: pomerium.extensions.ssh.StreamEvent
	(*DownstreamConnectEvent)(nil),                 // 10: pomerium.extensions.ssh.DownstreamConnectEvent
	(*ServerMessage)(nil),                          // 11: pomerium.extensions.ssh.ServerMessage
	(*AuthenticationResponse)(nil),                 // 12: pomerium.extensions.ssh.AuthenticationResponse
	(*ControlRequest)(nil),                         // 13: pomerium.extensions.ssh.ControlRequest
	(*AllowResponse)(nil),                          // 14: pomerium.extensions.ssh.AllowResponse
	(*Permissions)(nil),                            // 15: pomerium.extensions.ssh.Permissions
	(*DenyResponse)(nil),                           // 16: pomerium.extensions.ssh.DenyResponse
	(*InfoRequest)(nil),                            // 17: pomerium.extensions.ssh.InfoRequest
	(*InfoResponse)(nil),                           // 18: pomerium.extensions.ssh.InfoResponse
	(*KeyboardInteractiveInfoPrompts_Prompt)(nil),  // 19: pomerium.extensions.ssh.KeyboardInteractiveInfoPrompts.Prompt
	(*ControlRequest_CloseStream)(nil),             // 20: pomerium.extensions.ssh.ControlRequest.CloseStream
	nil,                                            // 21: pomerium.extensions.ssh.Permissions.ForceEnvEntry
	(*v3.GrpcService)(nil),                         // 22: envoy.config.core.v3.GrpcService
	(*anypb.Any)(nil),                              // 23: google.protobuf.Any
	(*timestamppb.Timestamp)(nil),                  // 24: google.protobuf.Timestamp
}
var file_api_extensions_filters_network_ssh_ssh_proto_depIdxs = []int32{
	2,  // 0: pomerium.extensions.ssh.CodecConfig.host_keys:type_name -> pomerium.extensions.ssh.HostKeyPair
	2,  // 1: pomerium.extensions.ssh.CodecConfig.user_ca_key:type_name -> pomerium.extensions.ssh.HostKeyPair
	22, // 2: pomerium.extensions.ssh.CodecConfig.grpc_service:type_name -> envoy.config.core.v3.GrpcService
	23, // 3: pomerium.extensions.ssh.AuthenticationRequest.method_request:type_name -> google.protobuf.Any
	19, // 4: pomerium.extensions.ssh.KeyboardInteractiveInfoPrompts.prompts:type_name -> pomerium.extensions.ssh.KeyboardInteractiveInfoPrompts.Prompt
	9,  // 5: pomerium.extensions.ssh.ClientMessage.event:type_name -> pomerium.extensions.ssh.StreamEvent
	3,  // 6: pomerium.extensions.ssh.ClientMessage.auth_request:type_name -> pomerium.extensions.ssh.AuthenticationRequest
	18, // 7: pomerium.extensions.ssh.ClientMessage.info_response:type_name -> pomerium.extensions.ssh.InfoResponse
	10, // 8: pomerium.extensions.ssh.StreamEvent.downstream_connected:type_name -> pomerium.extensions.ssh.DownstreamConnectEvent
	12, // 9: pomerium.extensions.ssh.ServerMessage.auth_response:type_name -> pomerium.extensions.ssh.AuthenticationResponse
	13, // 10: pomerium.extensions.ssh.ServerMessage.control_request:type_name -> pomerium.extensions.ssh.ControlRequest
	14, // 11: pomerium.extensions.ssh.AuthenticationResponse.allow:type_name -> pomerium.extensions.ssh.AllowResponse
	16, // 12: pomerium.extensions.ssh.AuthenticationResponse.deny:type_name -> pomerium.extensions.ssh.DenyResponse
	17, // 13: pomerium.extensions.ssh.AuthenticationResponse.info_request:type_name -> pomerium.extensions.ssh.InfoRequest
	20, // 14: pomerium.extensions.ssh.ControlRequest.close_stream:type_name -> pomerium.extensions.ssh.ControlRequest.CloseStream
	15, // 15: pomerium.extensions.ssh.AllowResponse.permissions:type_name -> pomerium.extensions.ssh.Permissions
	24, // 16: pomerium.extensions.ssh.Permissions.valid_before:type_name -> google.protobuf.Timestamp
	24, // 17: pomerium.extensions.ssh.Permissions.valid_after:type_name -> google.protobuf.Timestamp
	21, // 18: pomerium.extensions.ssh.Permissions.force_env:type_name -> pomerium.extensions.ssh.Permissions.ForceEnvEntry
	23, // 19: pomerium.extensions.ssh.InfoRequest.request:type_name -> google.protobuf.Any
	23, // 20: pomerium.extensions.ssh.InfoResponse.response:type_name -> google.protobuf.Any
	8,  // 21: pomerium.extensions.ssh.StreamManagement.ManageStream:input_type -> pomerium.extensions.ssh.ClientMessage
	11, // 22: pomerium.extensions.ssh.StreamManagement.ManageStream:output_type -> pomerium.extensions.ssh.ServerMessage
	22, // [22:23] is the sub-list for method output_type
	21, // [21:22] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_api_extensions_filters_network_ssh_ssh_proto_init() }
func file_api_extensions_filters_network_ssh_ssh_proto_init() {
	if File_api_extensions_filters_network_ssh_ssh_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CodecConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostKeyPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicKeyMethodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyboardInteractiveMethodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyboardInteractiveInfoPrompts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyboardInteractiveInfoPromptResponses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownstreamConnectEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Permissions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DenyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyboardInteractiveInfoPrompts_Prompt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControlRequest_CloseStream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*ClientMessage_Event)(nil),
		(*ClientMessage_AuthRequest)(nil),
		(*ClientMessage_InfoResponse)(nil),
	}
	file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*StreamEvent_DownstreamConnected)(nil),
	}
	file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*ServerMessage_AuthResponse)(nil),
		(*ServerMessage_ControlRequest)(nil),
	}
	file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*AuthenticationResponse_Allow)(nil),
		(*AuthenticationResponse_Deny)(nil),
		(*AuthenticationResponse_InfoRequest)(nil),
	}
	file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[13].OneofWrappers = []interface{}{
		(*ControlRequest_CloseStream_)(nil),
	}
	file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[15].OneofWrappers = []interface{}{}
	file_api_extensions_filters_network_ssh_ssh_proto_msgTypes[20].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_extensions_filters_network_ssh_ssh_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_extensions_filters_network_ssh_ssh_proto_goTypes,
		DependencyIndexes: file_api_extensions_filters_network_ssh_ssh_proto_depIdxs,
		MessageInfos:      file_api_extensions_filters_network_ssh_ssh_proto_msgTypes,
	}.Build()
	File_api_extensions_filters_network_ssh_ssh_proto = out.File
	file_api_extensions_filters_network_ssh_ssh_proto_rawDesc = nil
	file_api_extensions_filters_network_ssh_ssh_proto_goTypes = nil
	file_api_extensions_filters_network_ssh_ssh_proto_depIdxs = nil
}
