// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: github.com/pomerium/envoy-custom/api/x/recording/formats/ssh/raw_format.proto

package ssh

import (
	v3 "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
	ssh "github.com/pomerium/envoy-custom/api/extensions/filters/network/ssh"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Format int32

const (
	Format_UNKNOWN_FORMAT       Format = 0
	Format_RAW_FORMAT           Format = 1
	Format_ASCIICAST_FORMAT     Format = 2
	Format_RAW_ENCRYPTED_FORMAT Format = 3
)

// Enum value maps for Format.
var (
	Format_name = map[int32]string{
		0: "UNKNOWN_FORMAT",
		1: "RAW_FORMAT",
		2: "ASCIICAST_FORMAT",
		3: "RAW_ENCRYPTED_FORMAT",
	}
	Format_value = map[string]int32{
		"UNKNOWN_FORMAT":       0,
		"RAW_FORMAT":           1,
		"ASCIICAST_FORMAT":     2,
		"RAW_ENCRYPTED_FORMAT": 3,
	}
)

func (x Format) Enum() *Format {
	p := new(Format)
	*p = x
	return p
}

func (x Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Format) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_enumTypes[0].Descriptor()
}

func (Format) Type() protoreflect.EnumType {
	return &file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_enumTypes[0]
}

func (x Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Format.Descriptor instead.
func (Format) EnumDescriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_rawDescGZIP(), []int{0}
}

type PacketDirection int32

const (
	PacketDirection_UPSTREAM_TO_DOWNSTREAM PacketDirection = 0
	PacketDirection_DOWNSTREAM_TO_UPSTREAM PacketDirection = 1
)

// Enum value maps for PacketDirection.
var (
	PacketDirection_name = map[int32]string{
		0: "UPSTREAM_TO_DOWNSTREAM",
		1: "DOWNSTREAM_TO_UPSTREAM",
	}
	PacketDirection_value = map[string]int32{
		"UPSTREAM_TO_DOWNSTREAM": 0,
		"DOWNSTREAM_TO_UPSTREAM": 1,
	}
)

func (x PacketDirection) Enum() *PacketDirection {
	p := new(PacketDirection)
	*p = x
	return p
}

func (x PacketDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_enumTypes[1].Descriptor()
}

func (PacketDirection) Type() protoreflect.EnumType {
	return &file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_enumTypes[1]
}

func (x PacketDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketDirection.Descriptor instead.
func (PacketDirection) EnumDescriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_rawDescGZIP(), []int{1}
}

type Config struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	StorageDir        string                   `protobuf:"bytes,1,opt,name=storage_dir,json=storageDir,proto3" json:"storage_dir,omitempty"`
	GrpcService       *v3.GrpcService          `protobuf:"bytes,3,opt,name=grpc_service,json=grpcService,proto3" json:"grpc_service,omitempty"`
	CompressorLibrary *v3.TypedExtensionConfig `protobuf:"bytes,4,opt,name=compressor_library,json=compressorLibrary,proto3" json:"compressor_library,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetStorageDir() string {
	if x != nil {
		return x.StorageDir
	}
	return ""
}

func (x *Config) GetGrpcService() *v3.GrpcService {
	if x != nil {
		return x.GrpcService
	}
	return nil
}

func (x *Config) GetCompressorLibrary() *v3.TypedExtensionConfig {
	if x != nil {
		return x.CompressorLibrary
	}
	return nil
}

// This extension is added to [pomerium.extensions.ssh.UpstreamTarget] to enable session recording
// and configure related options.
type UpstreamTargetExtensionConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File basename for the recording, relative to the configured storage_dir.
	RecordingName string `protobuf:"bytes,1,opt,name=recording_name,json=recordingName,proto3" json:"recording_name,omitempty"`
	// Recording format
	Format        Format `protobuf:"varint,2,opt,name=format,proto3,enum=pomerium.x.recording.formats.ssh.Format" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamTargetExtensionConfig) Reset() {
	*x = UpstreamTargetExtensionConfig{}
	mi := &file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamTargetExtensionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamTargetExtensionConfig) ProtoMessage() {}

func (x *UpstreamTargetExtensionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamTargetExtensionConfig.ProtoReflect.Descriptor instead.
func (*UpstreamTargetExtensionConfig) Descriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_rawDescGZIP(), []int{1}
}

func (x *UpstreamTargetExtensionConfig) GetRecordingName() string {
	if x != nil {
		return x.RecordingName
	}
	return ""
}

func (x *UpstreamTargetExtensionConfig) GetFormat() Format {
	if x != nil {
		return x.Format
	}
	return Format_UNKNOWN_FORMAT
}

type RecordingMetadata struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	RecordingName    string                    `protobuf:"bytes,1,opt,name=recording_name,json=recordingName,proto3" json:"recording_name,omitempty"`
	Format           Format                    `protobuf:"varint,2,opt,name=format,proto3,enum=pomerium.x.recording.formats.ssh.Format" json:"format,omitempty"`
	UncompressedSize uint64                    `protobuf:"varint,3,opt,name=uncompressed_size,json=uncompressedSize,proto3" json:"uncompressed_size,omitempty"`
	StartTime        *timestamppb.Timestamp    `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime          *timestamppb.Timestamp    `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	LoginName        string                    `protobuf:"bytes,7,opt,name=login_name,json=loginName,proto3" json:"login_name,omitempty"`
	Upstream         *ssh.UpstreamTarget       `protobuf:"bytes,8,opt,name=upstream,proto3" json:"upstream,omitempty"`
	SessionId        string                    `protobuf:"bytes,9,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StreamId         uint64                    `protobuf:"varint,10,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	RouteName        string                    `protobuf:"bytes,11,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	PtyInfo          *ssh.SSHDownstreamPTYInfo `protobuf:"bytes,12,opt,name=pty_info,json=ptyInfo,proto3" json:"pty_info,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecordingMetadata) Reset() {
	*x = RecordingMetadata{}
	mi := &file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordingMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordingMetadata) ProtoMessage() {}

func (x *RecordingMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordingMetadata.ProtoReflect.Descriptor instead.
func (*RecordingMetadata) Descriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_rawDescGZIP(), []int{2}
}

func (x *RecordingMetadata) GetRecordingName() string {
	if x != nil {
		return x.RecordingName
	}
	return ""
}

func (x *RecordingMetadata) GetFormat() Format {
	if x != nil {
		return x.Format
	}
	return Format_UNKNOWN_FORMAT
}

func (x *RecordingMetadata) GetUncompressedSize() uint64 {
	if x != nil {
		return x.UncompressedSize
	}
	return 0
}

func (x *RecordingMetadata) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *RecordingMetadata) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *RecordingMetadata) GetLoginName() string {
	if x != nil {
		return x.LoginName
	}
	return ""
}

func (x *RecordingMetadata) GetUpstream() *ssh.UpstreamTarget {
	if x != nil {
		return x.Upstream
	}
	return nil
}

func (x *RecordingMetadata) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RecordingMetadata) GetStreamId() uint64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *RecordingMetadata) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *RecordingMetadata) GetPtyInfo() *ssh.SSHDownstreamPTYInfo {
	if x != nil {
		return x.PtyInfo
	}
	return nil
}

type Header struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	StartTime     int64                     `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // unix milliseconds
	PtyInfo       *ssh.SSHDownstreamPTYInfo `protobuf:"bytes,2,opt,name=pty_info,json=ptyInfo,proto3" json:"pty_info,omitempty"`
	Encrypted     bool                      `protobuf:"varint,3,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	Metadata      map[string]string         `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_rawDescGZIP(), []int{3}
}

func (x *Header) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Header) GetPtyInfo() *ssh.SSHDownstreamPTYInfo {
	if x != nil {
		return x.PtyInfo
	}
	return nil
}

func (x *Header) GetEncrypted() bool {
	if x != nil {
		return x.Encrypted
	}
	return false
}

func (x *Header) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Packet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time delta relative to the previous packet, or 0 for the first packet.
	// Encoding timestamps this way will compress better compared to full unix timestamps.
	TimeDeltaMs int64           `protobuf:"varint,1,opt,name=time_delta_ms,json=timeDeltaMs,proto3" json:"time_delta_ms,omitempty"`
	Direction   PacketDirection `protobuf:"varint,2,opt,name=direction,proto3,enum=pomerium.x.recording.formats.ssh.PacketDirection" json:"direction,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Packet_ChannelData
	//	*Packet_SshMessage
	Payload       isPacket_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_rawDescGZIP(), []int{4}
}

func (x *Packet) GetTimeDeltaMs() int64 {
	if x != nil {
		return x.TimeDeltaMs
	}
	return 0
}

func (x *Packet) GetDirection() PacketDirection {
	if x != nil {
		return x.Direction
	}
	return PacketDirection_UPSTREAM_TO_DOWNSTREAM
}

func (x *Packet) GetPayload() isPacket_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Packet) GetChannelData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*Packet_ChannelData); ok {
			return x.ChannelData
		}
	}
	return nil
}

func (x *Packet) GetSshMessage() []byte {
	if x != nil {
		if x, ok := x.Payload.(*Packet_SshMessage); ok {
			return x.SshMessage
		}
	}
	return nil
}

type isPacket_Payload interface {
	isPacket_Payload()
}

type Packet_ChannelData struct {
	// Raw contents of ChannelDataMsg. This is an optimization to avoid encoding the message
	// type, size, etc., since the majority of packets will be ChannelDataMsg.
	ChannelData []byte `protobuf:"bytes,3,opt,name=channel_data,json=channelData,proto3,oneof"`
}

type Packet_SshMessage struct {
	// Any SSH message
	SshMessage []byte `protobuf:"bytes,4,opt,name=ssh_message,json=sshMessage,proto3,oneof"`
}

func (*Packet_ChannelData) isPacket_Payload() {}

func (*Packet_SshMessage) isPacket_Payload() {}

var File_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto protoreflect.FileDescriptor

const file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_rawDesc = "" +
	"\n" +
	"Mgithub.com/pomerium/envoy-custom/api/x/recording/formats/ssh/raw_format.proto\x12 pomerium.x.recording.formats.ssh\x1aMgithub.com/pomerium/envoy-custom/api/extensions/filters/network/ssh/ssh.proto\x1a$envoy/config/core/v3/extension.proto\x1a'envoy/config/core/v3/grpc_service.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x01\n" +
	"\x06Config\x12\x1f\n" +
	"\vstorage_dir\x18\x01 \x01(\tR\n" +
	"storageDir\x12D\n" +
	"\fgrpc_service\x18\x03 \x01(\v2!.envoy.config.core.v3.GrpcServiceR\vgrpcService\x12Y\n" +
	"\x12compressor_library\x18\x04 \x01(\v2*.envoy.config.core.v3.TypedExtensionConfigR\x11compressorLibrary\"\x88\x01\n" +
	"\x1dUpstreamTargetExtensionConfig\x12%\n" +
	"\x0erecording_name\x18\x01 \x01(\tR\rrecordingName\x12@\n" +
	"\x06format\x18\x02 \x01(\x0e2(.pomerium.x.recording.formats.ssh.FormatR\x06format\"\xa4\x04\n" +
	"\x11RecordingMetadata\x12%\n" +
	"\x0erecording_name\x18\x01 \x01(\tR\rrecordingName\x12@\n" +
	"\x06format\x18\x02 \x01(\x0e2(.pomerium.x.recording.formats.ssh.FormatR\x06format\x12+\n" +
	"\x11uncompressed_size\x18\x03 \x01(\x04R\x10uncompressedSize\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1d\n" +
	"\n" +
	"login_name\x18\a \x01(\tR\tloginName\x12C\n" +
	"\bupstream\x18\b \x01(\v2'.pomerium.extensions.ssh.UpstreamTargetR\bupstream\x12\x1d\n" +
	"\n" +
	"session_id\x18\t \x01(\tR\tsessionId\x12\x1b\n" +
	"\tstream_id\x18\n" +
	" \x01(\x04R\bstreamId\x12\x1d\n" +
	"\n" +
	"route_name\x18\v \x01(\tR\trouteName\x12H\n" +
	"\bpty_info\x18\f \x01(\v2-.pomerium.extensions.ssh.SSHDownstreamPTYInfoR\aptyInfo\"\xa0\x02\n" +
	"\x06Header\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12H\n" +
	"\bpty_info\x18\x02 \x01(\v2-.pomerium.extensions.ssh.SSHDownstreamPTYInfoR\aptyInfo\x12\x1c\n" +
	"\tencrypted\x18\x03 \x01(\bR\tencrypted\x12R\n" +
	"\bmetadata\x18\x04 \x03(\v26.pomerium.x.recording.formats.ssh.Header.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x01\n" +
	"\x06Packet\x12\"\n" +
	"\rtime_delta_ms\x18\x01 \x01(\x03R\vtimeDeltaMs\x12O\n" +
	"\tdirection\x18\x02 \x01(\x0e21.pomerium.x.recording.formats.ssh.PacketDirectionR\tdirection\x12#\n" +
	"\fchannel_data\x18\x03 \x01(\fH\x00R\vchannelData\x12!\n" +
	"\vssh_message\x18\x04 \x01(\fH\x00R\n" +
	"sshMessageB\t\n" +
	"\apayload*\\\n" +
	"\x06Format\x12\x12\n" +
	"\x0eUNKNOWN_FORMAT\x10\x00\x12\x0e\n" +
	"\n" +
	"RAW_FORMAT\x10\x01\x12\x14\n" +
	"\x10ASCIICAST_FORMAT\x10\x02\x12\x18\n" +
	"\x14RAW_ENCRYPTED_FORMAT\x10\x03*I\n" +
	"\x0fPacketDirection\x12\x1a\n" +
	"\x16UPSTREAM_TO_DOWNSTREAM\x10\x00\x12\x1a\n" +
	"\x16DOWNSTREAM_TO_UPSTREAM\x10\x01B>Z<github.com/pomerium/envoy-custom/api/x/recording/formats/sshb\x06proto3"

var (
	file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_rawDescOnce sync.Once
	file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_rawDescData []byte
)

func file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_rawDescGZIP() []byte {
	file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_rawDescOnce.Do(func() {
		file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_rawDesc), len(file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_rawDesc)))
	})
	return file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_rawDescData
}

var file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_goTypes = []any{
	(Format)(0),                           // 0: pomerium.x.recording.formats.ssh.Format
	(PacketDirection)(0),                  // 1: pomerium.x.recording.formats.ssh.PacketDirection
	(*Config)(nil),                        // 2: pomerium.x.recording.formats.ssh.Config
	(*UpstreamTargetExtensionConfig)(nil), // 3: pomerium.x.recording.formats.ssh.UpstreamTargetExtensionConfig
	(*RecordingMetadata)(nil),             // 4: pomerium.x.recording.formats.ssh.RecordingMetadata
	(*Header)(nil),                        // 5: pomerium.x.recording.formats.ssh.Header
	(*Packet)(nil),                        // 6: pomerium.x.recording.formats.ssh.Packet
	nil,                                   // 7: pomerium.x.recording.formats.ssh.Header.MetadataEntry
	(*v3.GrpcService)(nil),                // 8: envoy.config.core.v3.GrpcService
	(*v3.TypedExtensionConfig)(nil),       // 9: envoy.config.core.v3.TypedExtensionConfig
	(*timestamppb.Timestamp)(nil),         // 10: google.protobuf.Timestamp
	(*ssh.UpstreamTarget)(nil),            // 11: pomerium.extensions.ssh.UpstreamTarget
	(*ssh.SSHDownstreamPTYInfo)(nil),      // 12: pomerium.extensions.ssh.SSHDownstreamPTYInfo
}
var file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_depIdxs = []int32{
	8,  // 0: pomerium.x.recording.formats.ssh.Config.grpc_service:type_name -> envoy.config.core.v3.GrpcService
	9,  // 1: pomerium.x.recording.formats.ssh.Config.compressor_library:type_name -> envoy.config.core.v3.TypedExtensionConfig
	0,  // 2: pomerium.x.recording.formats.ssh.UpstreamTargetExtensionConfig.format:type_name -> pomerium.x.recording.formats.ssh.Format
	0,  // 3: pomerium.x.recording.formats.ssh.RecordingMetadata.format:type_name -> pomerium.x.recording.formats.ssh.Format
	10, // 4: pomerium.x.recording.formats.ssh.RecordingMetadata.start_time:type_name -> google.protobuf.Timestamp
	10, // 5: pomerium.x.recording.formats.ssh.RecordingMetadata.end_time:type_name -> google.protobuf.Timestamp
	11, // 6: pomerium.x.recording.formats.ssh.RecordingMetadata.upstream:type_name -> pomerium.extensions.ssh.UpstreamTarget
	12, // 7: pomerium.x.recording.formats.ssh.RecordingMetadata.pty_info:type_name -> pomerium.extensions.ssh.SSHDownstreamPTYInfo
	12, // 8: pomerium.x.recording.formats.ssh.Header.pty_info:type_name -> pomerium.extensions.ssh.SSHDownstreamPTYInfo
	7,  // 9: pomerium.x.recording.formats.ssh.Header.metadata:type_name -> pomerium.x.recording.formats.ssh.Header.MetadataEntry
	1,  // 10: pomerium.x.recording.formats.ssh.Packet.direction:type_name -> pomerium.x.recording.formats.ssh.PacketDirection
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() {
	file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_init()
}
func file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_init() {
	if File_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto != nil {
		return
	}
	file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_msgTypes[4].OneofWrappers = []any{
		(*Packet_ChannelData)(nil),
		(*Packet_SshMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_rawDesc), len(file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_goTypes,
		DependencyIndexes: file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_depIdxs,
		EnumInfos:         file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_enumTypes,
		MessageInfos:      file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_msgTypes,
	}.Build()
	File_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto = out.File
	file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_goTypes = nil
	file_github_com_pomerium_envoy_custom_api_x_recording_formats_ssh_raw_format_proto_depIdxs = nil
}
