package(default_visibility = ["//visibility:public"])

filegroup(
    name = "llvm_toolchain_targets",
    srcs = [
        "@llvm_toolchain_llvm//:ar",
        "@llvm_toolchain_llvm//:as",
        "@llvm_toolchain_llvm//:bin/clang-19",
        "@llvm_toolchain_llvm//:bin/clang-apply-replacements",
        "@llvm_toolchain_llvm//:bin/clang-format",
        "@llvm_toolchain_llvm//:bin/clang-tidy",
        "@llvm_toolchain_llvm//:bin/lld",
        "@llvm_toolchain_llvm//:bin/llvm-cov",
        "@llvm_toolchain_llvm//:bin/llvm-profdata",
        "@llvm_toolchain_llvm//:bin/llvm-symbolizer",
        "@llvm_toolchain_llvm//:clang",
        "@llvm_toolchain_llvm//:dwp",
        "@llvm_toolchain_llvm//:extra_config_site",
        "@llvm_toolchain_llvm//:include",
        "@llvm_toolchain_llvm//:ld",
        "@llvm_toolchain_llvm//:lib_legacy",
        "@llvm_toolchain_llvm//:objcopy",
        "@llvm_toolchain_llvm//:strip",
    ],
)
