// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: github.com/pomerium/envoy-custom/api/extensions/transport_sockets/initial_metadata/initial_metadata.proto

package initial_metadata

import (
	v3 "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Underlying transport socket to wrap
	TransportSocket *v3.TransportSocket `protobuf:"bytes,1,opt,name=transport_socket,json=transportSocket,proto3" json:"transport_socket,omitempty"`
	// Required 4-byte magic prepended to any message that would be sent.
	Magic []byte `protobuf:"bytes,2,opt,name=magic,proto3" json:"magic,omitempty"`
	// Optional payload value to send if none is set for the connection.
	DefaultPayload *wrapperspb.BytesValue `protobuf:"bytes,3,opt,name=default_payload,json=defaultPayload,proto3" json:"default_payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetTransportSocket() *v3.TransportSocket {
	if x != nil {
		return x.TransportSocket
	}
	return nil
}

func (x *Config) GetMagic() []byte {
	if x != nil {
		return x.Magic
	}
	return nil
}

func (x *Config) GetDefaultPayload() *wrapperspb.BytesValue {
	if x != nil {
		return x.DefaultPayload
	}
	return nil
}

var File_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto protoreflect.FileDescriptor

const file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_rawDesc = "" +
	"\n" +
	"igithub.com/pomerium/envoy-custom/api/extensions/transport_sockets/initial_metadata/initial_metadata.proto\x126pomerium.extensions.transport_sockets.initial_metadata\x1a\x1fenvoy/config/core/v3/base.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1aAgithub.com/envoyproxy/protoc-gen-validate/validate/validate.proto\"\xe6\x01\n" +
	"\x06Config\x12Z\n" +
	"\x10transport_socket\x18\x01 \x01(\v2%.envoy.config.core.v3.TransportSocketB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x0ftransportSocket\x120\n" +
	"\x05magic\x18\x02 \x01(\fB\x1a\xfaB\x17z\x15\"\x11^[^\x04\x05PH\x14\x15\x16\x17].{3}$h\x04R\x05magic\x12N\n" +
	"\x0fdefault_payload\x18\x03 \x01(\v2\x1b.google.protobuf.BytesValueB\b\xfaB\x05z\x03\x18\xff\x01R\x0edefaultPayloadBTZRgithub.com/pomerium/envoy-custom/api/extensions/transport_sockets/initial_metadatab\x06proto3"

var (
	file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_rawDescOnce sync.Once
	file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_rawDescData []byte
)

func file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_rawDescGZIP() []byte {
	file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_rawDescOnce.Do(func() {
		file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_rawDesc), len(file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_rawDesc)))
	})
	return file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_rawDescData
}

var file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_goTypes = []any{
	(*Config)(nil),                // 0: pomerium.extensions.transport_sockets.initial_metadata.Config
	(*v3.TransportSocket)(nil),    // 1: envoy.config.core.v3.TransportSocket
	(*wrapperspb.BytesValue)(nil), // 2: google.protobuf.BytesValue
}
var file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_depIdxs = []int32{
	1, // 0: pomerium.extensions.transport_sockets.initial_metadata.Config.transport_socket:type_name -> envoy.config.core.v3.TransportSocket
	2, // 1: pomerium.extensions.transport_sockets.initial_metadata.Config.default_payload:type_name -> google.protobuf.BytesValue
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() {
	file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_init()
}
func file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_init() {
	if File_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_rawDesc), len(file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_goTypes,
		DependencyIndexes: file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_depIdxs,
		MessageInfos:      file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_msgTypes,
	}.Build()
	File_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto = out.File
	file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_goTypes = nil
	file_github_com_pomerium_envoy_custom_api_extensions_transport_sockets_initial_metadata_initial_metadata_proto_depIdxs = nil
}
