name: Test (Linux)

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-coverage:
    if: >-
      github.event_name != 'pull_request'
      || !contains(github.event.pull_request.labels.*.name, 'ci-not-ready')
    runs-on: envoy-custom-homelab
    timeout-minutes: 60
    permissions:
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: install dependencies
        run: sudo apt-get update && sudo apt-get -y install lcov zstd

      - name: setup bazel
        uses: bazel-contrib/setup-bazel@e8776f58fb6a6e9055cbaf1b38c52ccc5247e9c4
        with:
          bazelisk-version: 1.25.0

      - name: test
        run: |
          bazel coverage --config=buildbarn --test_output=errors //test/...
          tar xf bazel-out/_coverage/_coverage_report.dat ./lcov

      - name: upload to coveralls
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: lcov

  test-asan:
    if: >-
      github.event_name != 'pull_request'
      || !contains(github.event.pull_request.labels.*.name, 'ci-not-ready')
    runs-on: envoy-custom-homelab
    timeout-minutes: 60
    permissions:
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: setup bazel
        uses: bazel-contrib/setup-bazel@e8776f58fb6a6e9055cbaf1b38c52ccc5247e9c4
        with:
          bazelisk-version: 1.25.0

      - name: test
        id: asan-test
        run: bazel test --config=buildbarn  --config=asan --test_output=errors //test/...

  test-tsan:
    if: >-
      github.event_name != 'pull_request'
      || !contains(github.event.pull_request.labels.*.name, 'ci-not-ready')
    runs-on: envoy-custom-homelab
    timeout-minutes: 60
    permissions:
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: setup bazel
        uses: bazel-contrib/setup-bazel@e8776f58fb6a6e9055cbaf1b38c52ccc5247e9c4
        with:
          bazelisk-version: 1.25.0

      - name: test
        id: tsan-test
        run: bazel test --config=buildbarn  --config=tsan --test_output=errors //test/...

